# Generated by Django 5.2 on 2026-06-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=500)),
                ('stored_name', models.CharField(max_length=500)),
                ('relative_path', models.CharField(max_length=1000)),
                ('directory_type', models.CharField(choices=[('date', 'Date Directory'), ('edit', 'Edit Directory'), ('assets', 'Assets'), ('shared', 'Shared')], max_length=20)),
                ('date_directory', models.DateField(blank=True, null=True)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'file_records',
            },
        ),
    ]
