# Generated by Django 5.2 on 2026-07-01 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='filerecord',
            name='subdirectory',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.CreateModel(
            name='GlobalFileRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=500)),
                ('stored_name', models.CharField(max_length=500)),
                ('relative_path', models.CharField(max_length=1000)),
                ('subdirectory', models.CharField(blank=True, default='', max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'global_file_records',
            },
        ),
    ]
